In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("/content/restaurant_sales.csv")

In [ ]:
df.head(5)

         date   sales
0  2025-01-01  281.64
1  2025-01-02  212.74
2  2025-01-03  250.61
3  2025-01-04  253.38
4  2025-01-05  253.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    365 non-null    object
 1   sales   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB

In [ ]:
df['date']=pd.to_datetime(df['date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    365 non-null    datetime64[ns]
 1   sales   365 non-null    float64
dtypes: datetime64[ns](1), float64(1)
memory usage: 5.8 KB

In [ ]:
df.isnull().sum().sum()

np.int64(0)

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.index

RangeIndex(start=0, stop=365, step=1)

In [ ]:
df.index=df['date']

In [ ]:
df.head(5)

                 date   sales
date
2025-01-01 2025-01-01  281.64
2025-01-02 2025-01-02  212.74
2025-01-03 2025-01-03  250.61
2025-01-04 2025-01-04  253.38
2025-01-05 2025-01-05  253.00

In [ ]:
del df['date']

In [ ]:
df.head(5)

             sales
date
2025-01-01  281.64
2025-01-02  212.74
2025-01-03  250.61
2025-01-04  253.38
2025-01-05  253.00

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 365 entries, 2025-01-01 to 2025-12-31
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   sales   365 non-null    float64
dtypes: float64(1)
memory usage: 5.7 KB

In [ ]:
from statsmodels.tsa.stattools import adfuller

In [ ]:
result=adfuller(df['sales'])

In [ ]:
result[1]

np.float64(0.805321277897197)

In [ ]:
p_value=result[1]

In [ ]:
if p_value < 0.05:
  print("accepted as stationary")
else:
  print("rejected as non stationary")

rejected as non stationary